server:
  port: 9010
spring:
  application:
    name: gateway-api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes: # 网关路由配置
        - id: myrouter # 路由id，自定义，只要唯一即可
          uri: lb://businessservice  # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          ###匹配规则
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/api/** # 当请求的路径为/api/,/gate/开头的时，转发到 http://localhost:9010服务器上
#            - After=2017-01-20T17:42:47.789- 07:00[America/Denver]
          filters:
            - StripPrefix=1
#        - id: server
#          uri: http://localhost:9001
#          predicates:
#            - Path=/message
#            - Weight=group1, 75
#        - id: new_server
#          uri: http://localhost:9001
#          predicates:
#            - Path=/message
#            - Weight=group1, 25
#          filters:
#            - PrefixPath=/new
